arb-dir: lib/app/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/app/l10n
nullable-getter: false
untranslated-messages-file: untranslated_messages.json
preferred-supported-locales: [es, en]
synthetic-package: false
