name: qribar_cocina
description: Tu carta digital inteligente.
publish_to: 'none'
version: 1.6.0+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  audioplayers: ^6.4.0
  dio: ^5.8.0+1
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  permission_handler: ^12.0.0+1
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  wakelock_plus: ^1.2.10

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.9.0

flutter_icons:
  image_path: "assets/svg/logo_cut.png"
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/
    - assets/sounds/

flutter_gen:
  synthetic-package: false
