name: qribar_cocina
description: Tu carta digital inteligente.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  audioplayers: ^6.4.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  provider: ^6.1.4
  wakelock_plus: ^1.2.10

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/svg/logo_cut.png"
  android: true
  ios: true
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
